stages:
  - deploy

deploy_on_demo:
  stage: deploy
  script:
    - echo "Deploying to  server"
    - cd /var/www/payment/admin/front && export PATH="$PATH:/home/gitlab-runner/.nvm/versions/node/v18.19.1/bin" && make updatepm2
  only:
    - main
